inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "benchmark/**/*"
    - "google-cloud-firestore.gemspec"
    - "support/**/*"
    - "Rakefile"
    - "acceptance/**/*"
    - "conformance/**/*"
    - "test/**/*"

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - "lib/google/cloud/firestore/query.rb"
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 17
Metrics/PerceivedComplexity:
  Max: 17
Naming/FileName:
  Exclude:
    - "lib/google-cloud-firestore.rb"
Naming/RescuedExceptionsVariableName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
