inherit_gem:
  google-style: google-style.yml
Style/MutableConstant:
  Enabled: false
AllCops:
  Exclude:
  - google-cloud-container.gemspec
  - lib/google/**/*
  - Rakefile
  - test/**/*
  - acceptance/**/*
