AllCops:
  Exclude:
    - "gcloud.gemspec"
    - "Rakefile"
    - "lib/gcloud/proto/**/*"
    - "rakelib/**/*"
    - "rdoc/**/*"
    - "regression/**/*"
    - "test/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/NumericLiterals:
  Enabled: false
Style/SpaceAroundOperators:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/EmptyElse:
  Enabled: false
