inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "lib/**/*_pb.rb"
    - "proto_docs/**/*"
    - "test/**/*"

Metrics/AbcSize:
  Exclude:
    - "lib/google/cloud/dialogflow/v2/agents/*.rb"
    - "lib/google/cloud/dialogflow/v2/contexts/*.rb"
    - "lib/google/cloud/dialogflow/v2/entity_types/*.rb"
    - "lib/google/cloud/dialogflow/v2/intents/*.rb"
    - "lib/google/cloud/dialogflow/v2/session_entity_types/*.rb"
    - "lib/google/cloud/dialogflow/v2/sessions/*.rb"
Metrics/ClassLength:
  Exclude:
    - "lib/google/cloud/dialogflow/v2/agents/*.rb"
    - "lib/google/cloud/dialogflow/v2/contexts/*.rb"
    - "lib/google/cloud/dialogflow/v2/entity_types/*.rb"
    - "lib/google/cloud/dialogflow/v2/intents/*.rb"
    - "lib/google/cloud/dialogflow/v2/session_entity_types/*.rb"
    - "lib/google/cloud/dialogflow/v2/sessions/*.rb"
Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/google/cloud/dialogflow/v2/agents/*.rb"
    - "lib/google/cloud/dialogflow/v2/contexts/*.rb"
    - "lib/google/cloud/dialogflow/v2/entity_types/*.rb"
    - "lib/google/cloud/dialogflow/v2/intents/*.rb"
    - "lib/google/cloud/dialogflow/v2/session_entity_types/*.rb"
    - "lib/google/cloud/dialogflow/v2/sessions/*.rb"
Metrics/LineLength:
  Exclude:
    - "lib/google/cloud/dialogflow/v2/agents/*.rb"
    - "lib/google/cloud/dialogflow/v2/contexts/*.rb"
    - "lib/google/cloud/dialogflow/v2/entity_types/*.rb"
    - "lib/google/cloud/dialogflow/v2/intents/*.rb"
    - "lib/google/cloud/dialogflow/v2/session_entity_types/*.rb"
    - "lib/google/cloud/dialogflow/v2/sessions/*.rb"
    - "google-cloud-dialogflow-v2.gemspec"
Metrics/MethodLength:
  Exclude:
    - "lib/google/cloud/dialogflow/v2/agents/*.rb"
    - "lib/google/cloud/dialogflow/v2/contexts/*.rb"
    - "lib/google/cloud/dialogflow/v2/entity_types/*.rb"
    - "lib/google/cloud/dialogflow/v2/intents/*.rb"
    - "lib/google/cloud/dialogflow/v2/session_entity_types/*.rb"
    - "lib/google/cloud/dialogflow/v2/sessions/*.rb"
Metrics/PerceivedComplexity:
  Exclude:
    - "lib/google/cloud/dialogflow/v2/agents/*.rb"
    - "lib/google/cloud/dialogflow/v2/contexts/*.rb"
    - "lib/google/cloud/dialogflow/v2/entity_types/*.rb"
    - "lib/google/cloud/dialogflow/v2/intents/*.rb"
    - "lib/google/cloud/dialogflow/v2/session_entity_types/*.rb"
    - "lib/google/cloud/dialogflow/v2/sessions/*.rb"
Naming/FileName:
  Exclude:
    - "lib/google-cloud-dialogflow-v2.rb"
Style/CaseEquality:
  Exclude:
    - "lib/google/cloud/dialogflow/v2/agents/*.rb"
    - "lib/google/cloud/dialogflow/v2/contexts/*.rb"
    - "lib/google/cloud/dialogflow/v2/entity_types/*.rb"
    - "lib/google/cloud/dialogflow/v2/intents/*.rb"
    - "lib/google/cloud/dialogflow/v2/session_entity_types/*.rb"
    - "lib/google/cloud/dialogflow/v2/sessions/*.rb"
    - "lib/google/cloud/dialogflow/v2.rb"
Style/ModuleFunction:
  Enabled: false
