AllCops:
  Exclude:
    - "google-cloud-trace.gemspec"
    - "lib/google/devtools/**/*"
    - "Rakefile"
    - "test/**/*"

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/NumericLiterals:
  Enabled: false
Style/SpaceAroundOperators:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/EmptyLines:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Style/HashSyntax:
  Exclude:
    - "lib/google/cloud/trace/v1/**/*"
Metrics/LineLength:
  Exclude:
    - "lib/google/cloud/trace/v1/**/*"
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 25
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "lib/google/cloud/trace/v1/**/*"
Metrics/ParameterLists:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/FileName:
  Enabled: false # for lib/google-cloud-trace.rb file
Lint/RescueException:
  Enabled: false # for lib/google/cloud/logging/rails.rb file
