inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "google-cloud-language.gemspec"
    - "lib/google/**/*"
    - "Rakefile"
    - "test/**/*"
    - "acceptance/**/*"
Metrics/BlockLength:
  Exclude:
    - "samples/acceptance/*.rb"
Documentation:
  Enabled: false
