inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "Rakefile"
    - "test/**/*"
    - "acceptance/**/*"
Metrics/BlockLength:
  Exclude:
    - "samples/acceptance/*.rb"
Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/google-cloud-language.rb
