AllCops:
  Exclude:
    - "acceptance/**/*"
    - "integration/**/*"
    - "google-cloud-error_reporting.gemspec"
    - "lib/google/devtools/**/*"
    - "lib/google/cloud/error_reporting/v1beta1/**/*"
    - "lib/google/cloud/error_reporting/v1beta1.rb"
    - "Rakefile"
    - "support/**/*"
    - "test/**/*"

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/ClassVars:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 25
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/ParameterLists:
  Enabled: false
Layout/EmptyLines: # for the extra line between copyright and code
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/google-cloud-error_reporting.rb"
Lint/RescueException:
  Exclude:
    - "lib/google/cloud/error_reporting/middleware.rb"
Lint/AmbiguousOperator:
  Exclude:
    - "lib/google/cloud/error_reporting/project.rb"
