inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "acceptance/**/*"
    - "lib/google/cloud/translate/v3.rb"
    - "lib/google/cloud/translate/v3/**/*"
    - "support/**/*"
    - "test/**/*"
Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - "lib/google/cloud/translate/v2.rb"
Metrics/BlockLength:
  Exclude:
    - "google-cloud-translate.gemspec"
    - "Rakefile"
Metrics/MethodLength:
  Exclude:
    - "lib/google/cloud/translate.rb"
Naming/FileName:
  Exclude:
    - "lib/google-cloud-translate.rb"
