version: 2
jobs:
  test-2.5:
    working_directory: ~/GoogleCloudPlatform/google-cloud-ruby
    shell: /bin/bash --login
    docker:
    - image: circleci/ruby:2.5.1-stretch
    steps:
    - checkout
    - run: gem update --system
    - run: gem install bundler
    - run: bundle update
    - run: bundle exec rake circleci:build
    - run: bundle exec rake circleci:post
  test-2.4:
    working_directory: ~/GoogleCloudPlatform/google-cloud-ruby
    shell: /bin/bash --login
    docker:
    - image: circleci/ruby:2.4.4-stretch
    steps:
    - checkout
    - run: gem update --system
    - run: gem install bundler
    - run: bundle update
    - run: bundle exec rake circleci:build
    - run: bundle exec rake test:coveralls
  test-2.3:
    working_directory: ~/GoogleCloudPlatform/google-cloud-ruby
    shell: /bin/bash --login
    docker:
    - image: circleci/ruby:2.3.7-stretch
    steps:
    - checkout
    - run: gem update --system
    - run: gem install bundler
    - run: bundle update
    - run: bundle exec rake circleci:build
  release:
    working_directory: ~/GoogleCloudPlatform/google-cloud-ruby
    shell: /bin/bash --login
    docker:
    - image: circleci/ruby:2.5.1-stretch
    steps:
    - checkout
    - run: gem update --system
    - run: gem install bundler
    - run: bundle update
    - run: bundle exec rake circletest
#    - run: bundle exec rake circleci:release
workflows:
  version: 2
  ci:
    jobs:
      - test-2.5
      - test-2.4
      - test-2.3
  gem-release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /circletest-\S+/
#              only: /\S+\/v\S+/
notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=VdG8EataF3PrWBZOBH7Hr80BXUjYRLh7o
