inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "google-cloud-dataproc-v1beta2.gemspec"
    - "lib/**/*_pb.rb"
    - "proto_docs/**/*"
    - "test/**/*"
    - "acceptance/**/*"
    - "Rakefile"

Metrics/AbcSize:
  Exclude:
    - "lib/google/cloud/dataproc/v1beta2/autoscaling_policy_service/*.rb"
    - "lib/google/cloud/dataproc/v1beta2/cluster_controller/*.rb"
    - "lib/google/cloud/dataproc/v1beta2/job_controller/*.rb"
    - "lib/google/cloud/dataproc/v1beta2/workflow_template_service/*.rb"
Metrics/ClassLength:
  Exclude:
    - "lib/google/cloud/dataproc/v1beta2/autoscaling_policy_service/*.rb"
    - "lib/google/cloud/dataproc/v1beta2/cluster_controller/*.rb"
    - "lib/google/cloud/dataproc/v1beta2/job_controller/*.rb"
    - "lib/google/cloud/dataproc/v1beta2/workflow_template_service/*.rb"
Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/google/cloud/dataproc/v1beta2/autoscaling_policy_service/*.rb"
    - "lib/google/cloud/dataproc/v1beta2/cluster_controller/*.rb"
    - "lib/google/cloud/dataproc/v1beta2/job_controller/*.rb"
    - "lib/google/cloud/dataproc/v1beta2/workflow_template_service/*.rb"
Metrics/LineLength:
  Exclude:
    - "lib/google/cloud/dataproc/v1beta2/autoscaling_policy_service/*.rb"
    - "lib/google/cloud/dataproc/v1beta2/cluster_controller/*.rb"
    - "lib/google/cloud/dataproc/v1beta2/job_controller/*.rb"
    - "lib/google/cloud/dataproc/v1beta2/workflow_template_service/*.rb"
    - "google-cloud-dataproc-v1beta2.gemspec"
Metrics/MethodLength:
  Exclude:
    - "lib/google/cloud/dataproc/v1beta2/autoscaling_policy_service/*.rb"
    - "lib/google/cloud/dataproc/v1beta2/cluster_controller/*.rb"
    - "lib/google/cloud/dataproc/v1beta2/job_controller/*.rb"
    - "lib/google/cloud/dataproc/v1beta2/workflow_template_service/*.rb"
Metrics/PerceivedComplexity:
  Exclude:
    - "lib/google/cloud/dataproc/v1beta2/autoscaling_policy_service/*.rb"
    - "lib/google/cloud/dataproc/v1beta2/cluster_controller/*.rb"
    - "lib/google/cloud/dataproc/v1beta2/job_controller/*.rb"
    - "lib/google/cloud/dataproc/v1beta2/workflow_template_service/*.rb"
Naming/FileName:
  Exclude:
    - "lib/google-cloud-dataproc-v1beta2.rb"
Style/CaseEquality:
  Exclude:
    - "lib/google/cloud/dataproc/v1beta2/autoscaling_policy_service/*.rb"
    - "lib/google/cloud/dataproc/v1beta2/cluster_controller/*.rb"
    - "lib/google/cloud/dataproc/v1beta2/job_controller/*.rb"
    - "lib/google/cloud/dataproc/v1beta2/workflow_template_service/*.rb"
    - "lib/google/cloud/dataproc/v1beta2.rb"
Style/ModuleFunction:
  Enabled: false
