inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "acceptance/**/*"
    - "support/**/*"
    - "google-cloud-vision.gemspec"
    - "Rakefile"
    - "lib/google/cloud/vision.rb"
    - "lib/google/cloud/vision/v1.rb"
    - "lib/google/cloud/vision/v1/**/*"
    - "lib/google/cloud/vision/v1p3beta1.rb"
    - "lib/google/cloud/vision/v1p3beta1/**/*"
    - "test/**/*"

Documentation:
  Enabled: false
