AllCops:
  Exclude:
    - "google-cloud-vision.gemspec"
    - "lib/google/cloud/vision.rb"    
    - "lib/google/cloud/vision/*"
    - "lib/google/cloud/vision/v1/*pb.rb"
    - "lib/google/cloud/vision/v1/image_annotator_client.rb"
    - "lib/google/cloud/vision/v1/doc/**/*"
    - "Rakefile"
    - "test/**/*client_test.rb"
    - "acceptance/**/*smoke_test.rb"

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Metrics/BlockLength:
  Exclude:
    - "acceptance/google/cloud/vision/v1/image_annotator_feature_methods_test.rb"
    - "test/**/*"
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 25
Metrics/MethodLength:
  Max: 25
