inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "acceptance/**/*"
    - "integration/**/*"
    - "google-cloud-logging.gemspec"
    - "lib/google/logging/**/*"
    - "lib/google/cloud/logging/v2.rb"
    - "lib/google/cloud/logging/v2/**/*"
    - "Rakefile"
    - "support/**/*"
    - "test/**/*"

Documentation:
  Enabled: false

Lint/RescueException:
  Exclude:
    - "lib/google/cloud/logging/rails.rb"
Metrics/BlockLength:
  Exclude:
    - "lib/google-cloud-logging.rb"
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/PerceivedComplexity:
  Max: 15
Naming/FileName:
  Exclude:
    - "lib/google-cloud-logging.rb"
Style/CaseEquality:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MultilineWhenThen:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
