inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "grafeas-client.gemspec"
    - "lib/**/*"
    - "Rakefile"
    - "test/**/*"
    - "acceptance/**/*"

Documentation:
  Enabled: false
