inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "acceptance/**/*"
    - "lib/google/pubsub/**/*"
    - "lib/google/cloud/pubsub/v1.rb"
    - "lib/google/cloud/pubsub/v1/**/*"
    - "lib/google/iam/**/*"
    - "support/**/*"
    - "test/**/*"

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "google-cloud-pubsub.gemspec"
    - "Rakefile"
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Exclude:
    - "lib/google/cloud/pubsub.rb"
Naming/FileName:
  Exclude:
    - "lib/google-cloud-pubsub.rb"
