inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "google-cloud-app_engine.gemspec"
    - "Rakefile"
    - "acceptance/**/*"
    - "test/**/*"

Bundler/OrderedGems:
  Enabled: false
Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "samples/**/acceptance/*.rb"

Naming/FileName:
  Exclude:
    - "lib/google-cloud-app_engine.rb"

Style/AsciiComments:
  Enabled: false
