inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "google-cloud-bigtable.gemspec"
    - "lib/google-cloud-bigtable.rb"
    - "lib/google/bigtable/**/*"
    - "lib/google/cloud/bigtable/admin.rb"
    - "lib/google/cloud/bigtable/admin/**/*"
    - "lib/google/cloud/bigtable/v2.rb"
    - "lib/google/cloud/bigtable/v2/**/*"
    - "Rakefile"
    - "test/**/*"
    - "acceptance/**/*"
    - "conformance/**/*"
    - "samples/**/*"
    - "support/**/*"

Documentation:
  Enabled: true

Layout/AlignHash:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Max: 80
  IgnoredPatterns: ['(\A|\s)#']
Metrics/MethodLength:
  Max: 30
Naming/FileName:
  Exclude:
    - "lib/google-cloud-bigtable.rb"
Style/MethodCallWithArgsParentheses:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/RedundantFreeze:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/UnpackFirst:
  Enabled: false
Style/WordArray:
  Enabled: false
