inherit_gem:
    google-style: google-style.yml

Lint/UselessAssignment:
    Exclude:
        - "storage_remove_bucket_conditional_iam_binding.rb"
Lint/ShadowingOuterLocalVariable:
    Enabled: false
Metrics/AbcSize:
    Enabled: false
Metrics/BlockLength: 
    Enabled: false
Metrics/CyclomaticComplexity:
    Enabled: false
Metrics/LineLength:
    Exclude:
        - "acceptance/*.rb"
Metrics/MethodLength:
    Enabled: false
Naming/AccessorMethodName:
    Enabled: false
Style/GlobalVars:
    Exclude:
        - "acceptance/helper.rb"
Style/IfUnlessModifier:
    Enabled: false
Style/Next:
    Enabled: false
Style/SymbolProc:
    Enabled: false
