require: rubocop-minitest

inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "support/**/*"
    - "benchmark/**/*"

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "google-cloud-bigquery.gemspec"
    - "Rakefile"
Metrics/ClassLength:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/google-cloud-bigquery.rb"
Naming/UncommunicativeMethodParamName:
  Exclude:
    - "lib/google/cloud/bigquery/external.rb"
