AllCops:
  Exclude:
    - "gcloud.gemspec"
    - "Rakefile"
    - "test/**/*"
  TargetRubyVersion: 2.2

Documentation:
  Enabled: false

Layout/EmptyLines: # for the extra line between copyright and code
  Enabled: false
Metrics/LineLength:
  Exclude: 
    - "Gemfile"
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
