inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "google-cloud-access_approval-v1.gemspec"
    - "lib/**/*_pb.rb"
    - "proto_docs/**/*"
    - "test/**/*"
    - "acceptance/**/*"
    - "Rakefile"

Metrics/AbcSize:
  Exclude:
    - "lib/google/cloud/access_approval/v1/access_approval/*.rb"
Metrics/ClassLength:
  Exclude:
    - "lib/google/cloud/access_approval/v1/access_approval/*.rb"
Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/google/cloud/access_approval/v1/access_approval/*.rb"
Metrics/LineLength:
  Exclude:
    - "lib/google/cloud/access_approval/v1/access_approval/*.rb"
    - "google-cloud-access_approval-v1.gemspec"
Metrics/MethodLength:
  Exclude:
    - "lib/google/cloud/access_approval/v1/access_approval/*.rb"
Metrics/PerceivedComplexity:
  Exclude:
    - "lib/google/cloud/access_approval/v1/access_approval/*.rb"
Naming/FileName:
  Exclude:
    - "lib/google-cloud-access_approval-v1.rb"
Style/CaseEquality:
  Exclude:
    - "lib/google/cloud/access_approval/v1/access_approval/*.rb"
    - "lib/google/cloud/access_approval/v1.rb"
Style/ModuleFunction:
  Enabled: false
