inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "google-cloud-container_analysis.gemspec"
    - "lib/google/**/*"
    - "Rakefile"
    - "test/**/*"
    - "acceptance/**/*"

Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - "lib/google-cloud-container_analysis.rb"
