inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "google-cloud-env.gemspec"
    - "Rakefile"
    - "test/**/*"

Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/google-cloud-env.rb"
Style/IfUnlessModifier:
  Enabled: false
