name: PR Labels
on:
  pull_request_target:
    types: [labeled]
    branches:
      - master

jobs:
  ci-run:
    if: "github.repository == 'googleapis/google-cloud-ruby' && github.event.label.name == 'ci: run'"
    runs-on: ubuntu-latest
    steps:
    - name: execute
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.YOSHI_APPROVER_TOKEN }}
        script: |
          await github.issues.removeLabel({
            owner: 'googleapis',
            repo: 'google-cloud-ruby',
            issue_number: context.payload.pull_request.number,
            name: 'ci: run'
          });
          core.info('Removed "ci: run" label.');
          let prNum = context.payload.pull_request.number;
          let headRef = 'refs/pull/' + prNum + '/merge';
          let baseRef = context.payload.pull_request.base.sha;
          core.info('HEAD: ' + headRef);
          core.info('BASE: ' + baseRef);
          await github.actions.createWorkflowDispatch({
            owner: 'googleapis',
            repo: 'google-cloud-ruby',
            workflow_id: 'ci.yml',
            ref: context.ref,
            inputs: {
              head: headRef,
              base: baseRef
            }
          });
          core.info('Triggered CI job for PR ' + prNum);
