on:
  push:
    branches:
      - master
  pull_request:
name: system-tests-against-emulator
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - run: ruby --version
      - run: bash .github/workflows/system-tests-against-emulator.sh
