AllCops:
  Exclude:
    - "acceptance/**/*"
    - "google-cloud-speech.gemspec"
    - "lib/google/cloud/speech.rb"
    - "lib/google/cloud/speech/*"
    - "lib/google/cloud/speech/v1/*pb.rb"
    - "lib/google/cloud/speech/v1/speech_client.rb"
    - "lib/google/cloud/speech/v1/doc/**/*"
    - "Rakefile"
    - "test/google/cloud/speech/v1/**/*"

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - "acceptance/**/*"
    - "test/**/*"
